tasks:
  - init: mysqladmin -u root password 'gitpod' && composer creat-project
      phpmyadmin/phpmyadmin && composer creat-project --prefer-dist
      laravel/laravel
image:
  file: .gitpod.Dockerfile
